name = "GoAWS"
uuid = "00b10cec-568b-4d01-83ea-8604cd7f25ae"
authors = ["Beacon Biosignals", "Inc."]
version = "1.0.0-DEV"

[deps]
AWS = "fbe9abb3-538b-5e4e-ba9e-bc94f4f92ebc"
URIs = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
