# Based on the v0.4.5 config (https://github.com/Admiral-Piett/goaws/blob/v0.4.5/app/conf/goaws.yaml)
# Default existing queues and SNS topics were removed
Local:                              # Environment name that can be passed on the command line
  #     (i.e.: ./goaws [Local | Dev]  -- defaults to 'Local')
  Host: localhost                   # hostname of the goaws system  (for docker-compose this is the tag name of the container)
  # you can now use either 1 port for both sns and sqs or alternatively you can comment out Port and use SqsPort + SnsPort for compatibilyt with
  # yopa and (fage-sns + face-sqs).  If both ways are in the config file on the one "Port" will be used by GoAws
  Port: 4100                        # port to listen on.
  # SqsPort: 9324                     # alternate Sqs Port
  # SnsPort: 9292                     # alternate Sns Port
  Region: us-east-1
  AccountId: "100010001000"
  LogToFile: false                 # Log messages (true/false)
  LogFile: .st/goaws_messages.log  # Log filename (for message logging
  EnableDuplicates: false           # Enable or not deduplication based on messageDeduplicationId
  QueueAttributeDefaults:           # default attributes for all queues
    VisibilityTimeout: 30              # message visibility timeout
    ReceiveMessageWaitTimeSeconds: 0   # receive message max wait time
    MaximumMessageSize: 262144         # maximum message size (bytes)
  RandomLatency:                    # Parameters for introducing random latency into message queuing
    Min: 0                          # Desired latency in milliseconds, if min and max are zero, no latency will be applied.
    Max: 0                          # Desired latency in milliseconds
