---
    name: Format check
    on:
      pull_request:
        paths:
          - "**.jl"
          - ".github/workflows/julia-format.yml"
    concurrency:
      # Skip intermediate builds: always.
      # Cancel intermediate builds: only if it is a pull request build.
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
    jobs:
      format-check:
        name: Julia
        runs-on: ubuntu-latest
        steps:
          - uses: julia-actions/setup-julia@latest
            with:
              version: "1.9.3"
          - uses: actions/checkout@v4
          - uses: julia-actions/cache@v1
            with:
              cache-name: "${{ github.workflow }}-${{ github.job }}-${{ matrix.version }}-${{ matrix.runs-on }}-${{ matrix.arch }}"
              cache-compiled: true
              cache-registries: true # we are using a fixed version of the package, so this should be OK
          - name: Install JuliaFormatter
            shell: julia --color=yes --project=@format {0}
            run: |
              using Pkg
              Pkg.add(PackageSpec(; name="JuliaFormatter", version="1"))
          - name: Check formatting
            shell: julia --color=yes --project=@format {0}
            run: |
              using JuliaFormatter
              format("."; verbose=true) || exit(1)
          - uses: reviewdog/action-suggester@v1
            if: ${{ !cancelled() && github.event_name == 'pull_request' }}
            with:
              tool_name: JuliaFormatter
    